main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('customers', views.clients, name='customers'),
    path('customer/<int:pk_customer>', views.change_client, name='change_customer'),
    path('customer/new', views.new_client, name='new_customer'),
    path('apartments', views.apartments, name='apartments'),
    path('apartment/<int:pk_apartment>', views.change_apartment, name='change_apartment'),
    path('apartment/new', views.new_apartment, name='new_apartment'),
    path('clean_requests', views.clean_requests, name='clean_requests'),
    path('clean_request/<int:pk_clean_request>', views.change_clean_request, name='change_clean_request'),
    path('clean_request/new', views.new_clean_request, name='new_clean_request'),
    path('bron_lists', views.bron_lists, name='bron_lists'),
    path('bron_list/<int:pk_bron_list>', views.change_bron_list, name='change_bron_list'),
    path('bron_list/new', views.new_bron_list, name='new_bron_list'),
    path('resid_docs', views.resid_docs, name='resid_docs'),
    path('resid_doc/<int:pk_resid_doc>', views.change_resid_doc, name='change_resid_doc'),
    path('resid_doc/new', views.new_resid_doc, name='new_resid_doc'),
]

rental_department/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manage/', include('main.urls'), name='main'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('', include('main.urls'), name='redirect'),
    # path('', views.redir, name='redirect')
    # path('customers', views.customers, name='customers'),
]

main/forms.py
from django.forms import ModelForm, DateField, SelectDateWidget, ModelChoiceField, Form
from .models import (CleanRequest, Customer, Apartment, BronList, ResidDoc, CleanWorker, AdminWorker)
from datetime import datetime


class CustomerForm(ModelForm):

    class Meta:
        model = Customer
        fields = ['customer_name', 'customer_phone', 'customer_pasport']
        labels = {'customer_name': 'ФИО',
                  'customer_phone': 'Телефон',
                  'customer_pasport': 'Пасспортные данные'}


class ApartmentForm(ModelForm):
    class Meta:
        model = Apartment
        fields = ['apartment_rooms', 'apartment_price', 'apartment_status']
        labels = {'apartment_rooms': 'Количество комнат',
                  'apartment_price': 'Цена за сутки',
                  'apartment_status': 'Статус'}


class CleanRequestForm(ModelForm):
    START_DATE = 2000
    clean_request_date = DateField(
        widget=SelectDateWidget(years=[i for i in range(START_DATE, int(datetime.today().year) + 1)]),
        label='Дата запроса',
        initial=datetime.today()
    )
    id_apartment = ModelChoiceField(queryset=Apartment.objects.all(), empty_label=None, label='Апартаменты')
    id_clean_worker = ModelChoiceField(queryset=CleanWorker.objects.all(), empty_label=None, label='Уборщик')
    id_admin_worker = ModelChoiceField(queryset=AdminWorker.objects.all(), empty_label=None, label='Администратор')

    class Meta:
        model = CleanRequest

        fields = ['clean_request_date', 'id_apartment', 'id_clean_worker',  'id_admin_worker']
        labels = {'clean_request_date': 'Дата запроса',
                  'id_apartment': 'Апартаменты',
                  'id_clean_worker': 'Уборщик',
                  'id_admin_worker': 'Администратор'}


class BronListForm(ModelForm):
    id_customer = ModelChoiceField(queryset=Customer.objects.all(), empty_label=None, label='Клиент')
    id_apartment = ModelChoiceField(queryset=Apartment.objects.all(), empty_label=None, label='Апартаменты')
    id_admin_worker = ModelChoiceField(queryset=AdminWorker.objects.all(), empty_label=None, label='Администратор')

    class Meta:
        model = BronList

        fields = ['bron_number', 'id_customer', 'id_apartment', 'id_admin_worker']
        labels = {'bron_number': '№',
                  'id_customer': 'Клиент',
                  'id_apartment': 'Апартаменты',
                  'id_admin_worker': 'Администратор'}


class ResidDocForm(ModelForm):
    START_DATE = 2000
    doc_date_start = DateField(
        widget=SelectDateWidget(years=[i for i in range(START_DATE, int(datetime.today().year) + 1)]),
        label='Дата заселения',
    )
    doc_date_end = DateField(
        widget=SelectDateWidget(years=[i for i in range(START_DATE, int(datetime.today().year) + 1)]),
        label='Дата выселения',
        initial=datetime.today()
    )

    id_customer = ModelChoiceField(queryset=Customer.objects.all(), empty_label=None, label='Клиент')
    id_apartment = ModelChoiceField(queryset=Apartment.objects.all(), empty_label=None, label='Апартаменты')
    id_admin_worker = ModelChoiceField(queryset=AdminWorker.objects.all(), empty_label=None, label='Администратор')

    class Meta:
        model = ResidDoc

        fields = ['doc_date_start', 'doc_date_end', 'id_customer', 'id_apartment', 'doc_price', 'id_admin_worker']
        labels = {'doc_date_start': 'Дата заселения',
                  'doc_date_end': 'Дата выселения',
                  'id_customer': 'Клиент',
                  'id_apartment': 'Апартаменты',
                  'doc_price': 'Цена',
                  'id_admin_worker': 'Администратор'}

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from .models import (AdminWorker, CleanRequest, Customer, Apartment, BronList,
                     CleanWorker, ResidDoc, UserExtent)
from .forms import (CustomerForm, ApartmentForm, CleanRequestForm,
                    BronListForm, ResidDocForm)
from .parse_request import get_employee
from django.http import HttpResponse, HttpResponseRedirect


def login_user(request):
    if request.method == 'GET':
        return render(request, 'main/log_in.html', {'form': AuthenticationForm()})
    elif request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'main/log_in.html',
                          {'form': AuthenticationForm(), 'error': "Неверное имя или пароль"})
        else:
            login(request, user)
            return redirect('main:home')


@login_required()
def home(request):
    if request.method == 'GET':
        employee_type, employee_id, employee_name = get_employee(request)
        dictionary = {'employee_type': employee_type,
                      'employee_id': employee_id,
                      'employee_name': employee_name}
        if employee_type == 'Администратор':
            dictionary.update({'customers': Customer.objects.all()})

        return render(request, 'main/home.html', dictionary)
    elif request.method == 'POST':
        pass


@login_required
def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('login')


def redir(request):
    if request.method == 'GET':
        return redirect('main:home')


@login_required()
def clients(request):
    if request.method == 'GET':
        employee_type, employee_id, employee_name = get_employee(request)
        dictionary = {'employee_type': employee_type,
                      'employee_id': employee_id,
                      'employee_name': employee_name}
        if employee_type == 'Администратор':
            dictionary.update({'customers': Customer.objects.all()})
        form = CustomerForm()
        dictionary.update({'form': form})
        return render(request, 'main/customers.html', dictionary)
    elif request.method == "POST":
        pass


@login_required()
def change_client(request, pk_customer):
    employee_type, employee_id, employee_name = get_employee(request)
    dictionary = {'employee_type': employee_type,
                  'employee_id': employee_id,
                  'employee_name': employee_name}
    if pk_customer:
        client_ = Customer.objects.get(id_customer=pk_customer)
        if request.method == 'GET':
            form = CustomerForm(instance=client_)
            dictionary.update({'form': form})
            return render(request, 'main/change_customer.html', dictionary)
        elif request.method == 'POST':
            if 'save-client' in request.POST:
                form = CustomerForm(request.POST, instance=client_)
                form.save()
                return redirect('main:customers')
    else:
        if request.method == 'GET':
            form = CustomerForm()
            dictionary.update({'form': form})
            return render(request, 'main/change_customer.html', dictionary)
        elif request.method == 'POST':
            if 'save-client' in request.POST:
                form = CustomerForm(request.POST)
                form.save()
                return redirect('main:customers')


@login_required
def new_client(request):
    if request.method == 'GET':
        return change_client(request, None)
    elif request.method == 'POST':
        return change_client(request, None)


@login_required
def apartments(request):
    if request.method == 'GET':
        employee_type, employee_id, employee_name = get_employee(request)
        dictionary = {'employee_type': employee_type,
                      'employee_id': employee_id,
                      'employee_name': employee_name}
        if employee_type == 'Администратор':
            dictionary.update({'apartments': Apartment.objects.all()})
        form = ApartmentForm()
        dictionary.update({'form': form})
        return render(request, 'main/apartments.html', dictionary)
    elif request.method == "POST":
        pass


@login_required()
def change_apartment(request, pk_apartment):
    employee_type, employee_id, employee_name = get_employee(request)
    dictionary = {'employee_type': employee_type,
                  'employee_id': employee_id,
                  'employee_name': employee_name}
    if pk_apartment:
        apartment_ = Apartment.objects.get(id_apartment=pk_apartment)
        if request.method == 'GET':
            form = ApartmentForm(instance=apartment_)
            dictionary.update({'form': form})
            return render(request, 'main/change_apartment.html', dictionary)
        elif request.method == 'POST':
            if 'save-apartment' in request.POST:
                form = ApartmentForm(request.POST, instance=apartment_)
                form.save()
                return redirect('main:apartments')
    else:
        if request.method == 'GET':
            form = ApartmentForm()
            dictionary.update({'form': form})
            return render(request, 'main/change_apartment.html', dictionary)
        elif request.method == 'POST':
            if 'save-apartment' in request.POST:
                form = ApartmentForm(request.POST)
                form.save()
                return redirect('main:apartments')


@login_required
def new_apartment(request):
    if request.method == 'GET':
        return change_apartment(request, None)
    elif request.method == 'POST':
        return change_apartment(request, None)


@login_required()
def clean_requests(request):
    if request.method == 'GET':
        employee_type, employee_id, employee_name = get_employee(request)
        dictionary = {'employee_type': employee_type,
                      'employee_id': employee_id,
                      'employee_name': employee_name}
        if employee_type == 'Администратор':
            dictionary.update({'clean_requests': CleanRequest.objects.all()})
        elif employee_type == 'Уборщик':
            dictionary.update({'clean_requests': CleanRequest.objects.filter(id_clean_worker=employee_id)})
        form = CleanRequestForm()
        dictionary.update({'form': form})
        return render(request, 'main/clean_requests.html', dictionary)
    elif request.method == "POST":
        pass


@login_required()
def change_clean_request(request, pk_clean_request):
    employee_type, employee_id, employee_name = get_employee(request)
    dictionary = {'employee_type': employee_type,
                  'employee_id': employee_id,
                  'employee_name': employee_name}
    if pk_clean_request:
        clean_request_ = CleanRequest.objects.get(id_clean_request=pk_clean_request)
        if request.method == 'GET':
            form = CleanRequestForm(instance=clean_request_)
            dictionary.update({'form': form})
            return render(request, 'main/change_clean_request.html', dictionary)
        elif request.method == 'POST':
            if 'save-clean-request' in request.POST:
                form = CleanRequestForm(request.POST, instance=clean_request_)
                form.save()
                return redirect('main:clean_requests')
            elif 'close-clean-request' in request.POST:
                pk_apartment = str(clean_request_.id_apartment)

                pk_apartment = pk_apartment[:12].split('.')[0]
                apartment_ = Apartment.objects.get(id_apartment=pk_apartment)
                apartment_.apartment_status = 'Готов'
                apartment_.save()

                clean_request_.delete()

                return redirect('main:clean_requests')
    else:
        if request.method == 'GET':
            form = CleanRequestForm()
            dictionary.update({'form': form})
            dictionary.update({'new': True})
            return render(request, 'main/change_clean_request.html', dictionary)
        elif request.method == 'POST':
            if 'save-clean-request' in request.POST:
                form = CleanRequestForm(request.POST)
                form.save()

                pk_apartment = str(form.cleaned_data.get('id_apartment'))
                pk_apartment = pk_apartment[:12].split('.')[0]
                apartment_ = Apartment.objects.get(id_apartment=pk_apartment)
                apartment_.apartment_status = 'Нуждается в уборке'
                apartment_.save()

                return redirect('main:clean_requests')


@login_required()
def new_clean_request(request):
    if request.method == 'GET':
        return change_clean_request(request, None)
    elif request.method == "POST":
        return change_clean_request(request, None)


@login_required()
def bron_lists(request):
    if request.method == 'GET':
        employee_type, employee_id, employee_name = get_employee(request)
        dictionary = {'employee_type': employee_type,
                      'employee_id': employee_id,
                      'employee_name': employee_name}
        if employee_type == 'Администратор':
            dictionary.update({'bron_lists': BronList.objects.all()})
        form = BronListForm()
        dictionary.update({'form': form})
        return render(request, 'main/bron_lists.html', dictionary)
    elif request.method == "POST":
        pass


@login_required()
def change_bron_list(request, pk_bron_list):
    employee_type, employee_id, employee_name = get_employee(request)
    dictionary = {'employee_type': employee_type,
                  'employee_id': employee_id,
                  'employee_name': employee_name}
    if pk_bron_list:

main/templates/main/apartments.html
{% extends 'base.html' %}
{% block content %}

{% if employee_type == 'Администратор' %}
    <h1>Список апартаментов</h1><br>


    <div class="container">
        <div class="row">
            <div class="col-lg-1 col-md-1 col-sm-1">
                <a class="btn btn-primary" href="{% url 'main:new_apartment' %}">Добавить</a>
                <br>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8"><br><br>
                <div class="list-group list-scroll">
                    {% for apartment in apartments %}
                        <a href="{% url 'main:change_apartment' apartment.id_apartment %}"
                           class="list-group-item list-group-item-action">
                            Количетсво комнат: {{ apartment.apartment_rooms }}<br>
                            Цена за сутки: {{ apartment.apartment_price }}<br>
                            Статус: {{ apartment.apartment_status }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>
{% endif %}

{% endblock %}

main/templates/main/bron_lists.html
{% extends 'base.html' %}
{% block content %}

{% if employee_type == 'Администратор' %}
    <h1>Список бронирований</h1><br>


    <div class="container">
        <div class="row">
            <div class="col-lg-1 col-md-1 col-sm-1">
                <a class="btn btn-primary" href="{% url 'main:new_bron_list' %}">Добавить</a>
                <br>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8"><br><br>
                <div class="list-group list-scroll">
                    {% for bron_list in bron_lists %}
                        <a href="{% url 'main:change_bron_list' bron_list.id_bron_list %}"
                           class="list-group-item list-group-item-action">
                            №: {{ bron_list.bron_number }}<br>
                            Клиент: {{ bron_list.id_customer }}<br>
                            Апартаменты: {{ bron_list.id_apartment }}<br>
                            Администратор: {{ bron_list.id_admin_worker }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>
{% endif %}

{% endblock %}

main/templates/main/change_apartment.html
{% extends 'base.html' %}
{% block content %}

    <h1>Апартаменты</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="save-apartment" class="btn btn-secondary">Сохранить</button>

    </form>

{% endblock %}

main/templates/main/change_bron_list.html
{% extends 'base.html' %}
{% block content %}

    <h1>Бронирование</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="save-bron-list" class="btn btn-secondary">Сохранить</button>
        {% if not new %}
        <button type="submit" name="close-bron-list" class="btn btn-secondary">Отменить</button>
        {% endif %}

    </form>

{% endblock %}

main/templates/main/change_clean_request.html
{% extends 'base.html' %}
{% block content %}

    <h1>Запрос на уборку</h1>

    <form method="post">
        {% csrf_token %}
        {% if employee_type == 'Администратор' %}
        {{ form.as_p }}
        <button type="submit" name="save-clean-request" class="btn btn-secondary">Сохранить</button>
        {% endif %}
        {% if not new %}
        <button type="submit" name="close-clean-request" class="btn btn-secondary">Пометить выполненным</button>
        {% endif %}

    </form>

{% endblock %}

main/templates/main/change_customer.html
{% extends 'base.html' %}
{% block content %}

    <h1>Клиент</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="save-client" class="btn btn-secondary">Сохранить</button>

    </form>

{% endblock %}

main/templates/main/change_resid_doc.html
{% extends 'base.html' %}
{% block content %}

    <h1>Документ о проживании</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="save-resid-doc" class="btn btn-secondary">Сохранить</button>
        {% if not new %}
        <button type="submit" name="close-resid-doc" class="btn btn-secondary">Удалить</button>
        {% endif %}

    </form>

{% endblock %}

main/templates/main/clean_requests.html
{% extends 'base.html' %}
{% block content %}

{% if employee_type == 'Администратор' or employee_type == 'Уборщик' %}
    <h1>Список запросов на уборку</h1><br>


    <div class="container">
        <div class="row">
            <div class="col-lg-1 col-md-1 col-sm-1">
                {% if employee_type == 'Администратор' %}
                <a class="btn btn-primary" href="{% url 'main:new_clean_request' %}">Добавить</a>
                {% endif %}
                <br>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8"><br><br>
                <div class="list-group list-scroll">
                    {% for clean_request in clean_requests %}
                        <a href="{% url 'main:change_clean_request' clean_request.id_clean_request %}"
                           class="list-group-item list-group-item-action">
                            Дата запроса: {{ clean_request.clean_request_date }}<br>
                            Апартаменты: {{ clean_request.id_apartment }}<br>
                            Уборщик: {{ clean_request.id_clean_worker }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>
{% endif %}

{% endblock %}

main/templates/main/customers.html
{% extends 'base.html' %}
{% block content %}

{% if employee_type == 'Администратор' %}
    <h1>Список клиентов</h1><br>


    <div class="container">
        <div class="row">
            <div class="col-lg-1 col-md-1 col-sm-1">
                <a class="btn btn-primary" href="{% url 'main:new_customer' %}">Добавить клиента</a>
                <br>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8"><br><br>
                <div class="list-group list-scroll">
                    {% for customer in customers %}
                        <a href="{% url 'main:change_customer' customer.id_customer %}"
                           class="list-group-item list-group-item-action">
                            {{ customer.customer_name }}<br>
                            Телефон: {{ customer.customer_phone }}<br>
                            Пасспортные данные: {{ customer.customer_pasport }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>
{% endif %}

{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% block content %}
    {% if employee_type == 'Администратор' %}
        <h1>Admin worker</h1><br>
    {% elif employee_type == 'Уборщик' %}
        <h1>Clean Worker</h1><br>
    {% endif %}
    <h3>{{ employee_id }}</h3>
    <h3>{{ employee_name }}</h3>
    {% for elem in customers %}
        {{ elem }}
    <br>
    {% endfor %}

{% endblock %}

main/templates/main/log_in.html
{% extends 'base.html' %}
{% block content %}

    <h1>Войти</h1>

    <h3>{{ error }}</h3>

    <form  action="{% url 'login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Войти</button>
    </form>

{% endblock %}

main/templates/main/resid_docs.html
{% extends 'base.html' %}
{% block content %}

{% if employee_type == 'Администратор' %}
    <h1>Документы о проживании</h1><br>


    <div class="container">
        <div class="row">
            <div class="col-lg-1 col-md-1 col-sm-1">
                <a class="btn btn-primary" href="{% url 'main:new_resid_doc' %}">Добавить</a>
                <br>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8"><br><br>
                <div class="list-group list-scroll">
                    {% for resid_doc in resid_docs %}
                        <a href="{% url 'main:change_resid_doc' resid_doc.id_doc %}"
                           class="list-group-item list-group-item-action">
                            Дата заселения: {{ resid_doc.doc_date_start }}<br>
                            Дата выселения: {{ resid_doc.doc_date_end }}<br>
                            Клиент: {{ resid_doc.id_customer }}<br>
                            Апартаменты: {{ resid_doc.id_apartment }}<br>
                            Цена: {{ resid_doc.doc_price }}<br>
                            Администратор: {{ resid_doc.id_admin_worker }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>
{% endif %}

{% endblock %}